before_script:
  - pip install tox

test_python35:
  stage: test
  image: python:3.5
  script: tox -e 'py35-django{111,200,210,220}'

test_python36:
  stage: test
  image: python:3.6
  script: tox -e 'py36-django{111,200,210,220}'

test_python37:
  stage: test
  image: python:3.7
  script: tox -e 'py37-django{200,210,220}'

test_pypy35:
  stage: test
  image: pypy:3-5
  script: tox -e 'pypy3-django{111,200,210,220}'
