stages:
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

test:
  stage: test
  image: $IMAGE
  script:
    - pip install tox
    - tox -e $TOX_ENVS
  parallel:
    matrix:
      - IMAGE: python:3.7
        TOX_ENVS: py37-django{320}-wagtail{215,300}

      - IMAGE: python:3.8
        TOX_ENVS: py38-django{320}-wagtail{215,300},py38-django{400}-wagtail{300}

      - IMAGE: python:3.9
        TOX_ENVS: py39-django{320}-wagtail{215,300},py39-django{400}-wagtail{300}

      - IMAGE: python:3.10
        TOX_ENVS: py310-django{400}-wagtail{300}
