stages:
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

test:
  stage: test
  image: $IMAGE
  script:
    - pip install tox
    - tox -e $TOX_ENVS
  parallel:
    matrix:
      - IMAGE: python:3.7
        TOX_ENVS: py37-django{220,300}-wagtail{209,210,211,212,213},py37-django{310}-wagtail{211,212,213},py37-django{320}-wagtail{213}

      - IMAGE: python:3.8
        TOX_ENVS: py38-django{220,300}-wagtail{209,210,211,212,213},py38-django{310}-wagtail{211,212,213},py38-django{320}-wagtail{213}

      - IMAGE: python:3.9
        TOX_ENVS: py39-django{220,300}-wagtail{209,210,211,212,213},py39-django{310}-wagtail{211,212,213},py39-django{320}-wagtail{213}

      - IMAGE: pypy:3
        TOX_ENVS: pypy3-django{220,300}-wagtail{209,210,211,212,213},pypy3-django{310}-wagtail{211,212,213},pypy3-django{320}-wagtail{213}
